import type { Metadata } from "next";
import "./globals.css";

import "@mantine/core/styles.css";
import "@mantine/notifications/styles.css";
import "mantine-datatable/styles.layer.css";
import "@mantine/dropzone/styles.css";

import {
  ColorSchemeScript,
  MantineProvider,
  Typography,
  mantineHtmlProps,
} from "@mantine/core";
import { Notifications } from "@mantine/notifications";
import { ModalsProvider } from "@mantine/modals";
import ProgressProviders from "@/components/progress-provider";
import { Poppins } from "next/font/google";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" {...mantineHtmlProps} className={poppins.className}>
      <head>
        <ColorSchemeScript />
      </head>
      <body>
        <MantineProvider theme={{ fontFamily: poppins.style.fontFamily }}>
          <Notifications position="top-center" />
          <Typography />
          <ModalsProvider>
            <ProgressProviders>{children}</ProgressProviders>
          </ModalsProvider>
        </MantineProvider>
      </body>
    </html>
  );
}
